### ISSUE TITLE
Swift 2.2 support in 1.x release branch

### ISSUE THREAD

**Issue by amarcadet** [devlucky/Kakapo#133]
Hi!

Do you plan to support Swift 2.2 in 1.x release branch?
There are just couple of lines that prevent 1.0.1 to be compatible with Swift 2.2.

I could make such PR but I'm not sure which branch I should use, could you point me the right one?

Thanks

**Comment by MP0w** [comment]
Hi, we didn't consider it because would be probably used by few projects. However if it's useful for you and other people we are happy to accept a PR. The branch is currently `swift2.3` but we can eventually rename it `legacy-swift`.
We would have to make sure we add a job to the ci macro to test with Xcode 7.

**Comment by amarcadet** [comment]
Thanks for the quick reply!

I can't currently migrate my project to Xcode 8 and Swift 2.3 (close deadline) but I need the bugfix shipped in 1.0.1 (I was using 0.2.0).
I might be the only one with such bad luck but if you're ok I can work on this PR.
The idea is not to add feature for Swift 2.x but rather offer better backward compatibility.

I let you rename the branch and will push to it ASAP (probably not today since I'm in a hurry right now).

Regarding ci configuration, I don't know anything, I appreciate if you could assist me on that point!

**Comment by MP0w** [comment]
Sure, will rename the branch tomorrow. I can take care of the ci!

**Comment by MP0w** [comment]
@amarcadet I renamed the branch to `feature/legacy-swift`

**Comment by MP0w** [comment]
# TODO:
- [x] Restore Swift 2.2 support (@amarcadet)
- [x] Update README (instead of Swift 2.3 support, Swift 2.2 and 2.3 support)
- [x] Add Xcode 7 job to build matrix (@MP0w)
- [x] Release 1.0.X to Cocoapods

**Comment by MP0w** [comment]
Hi @amarcadet, are you still interested to add support for swift 2.2?

**Comment by amarcadet** [comment]
Yes sorry for the delay, I'm doing immediately!

**Comment by MP0w** [comment]
Don't worry! Was just wondering if was still needed! 👌

**Comment by joanromano** [comment]
@amarcadet let us know if we can help 👍

**Comment by amarcadet** [comment]
Hi again, PR is open, let me know if I need to do anything!
Thanks!

**Comment by joanromano** [comment]
Released, thanks a lot @amarcadet 🎉 🚀  https://github.com/devlucky/Kakapo/releases/tag/1.1.1
